export const hotels = [
  {
    id: "hotel-1",
    name: "Taj Bengal",
    city: "Kolkata",
    price: 5000,
    rating: 4.8,
    location: "Alipore",
    availableRooms: 20,
    createdBy: "admin-1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "hotel-2",
    name: "ITC Royal Bengal",
    city: "Kolkata",
    price: 7500,
    rating: 4.9,
    location: "EM Bypass",
    availableRooms: 15,
    createdBy: "admin-1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "hotel-3",
    name: "The Oberoi Grand",
    city: "Kolkata",
    price: 6500,
    rating: 4.7,
    location: "Esplanade",
    availableRooms: 12,
    createdBy: "admin-1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "hotel-4",
    name: "Novotel Kolkata",
    city: "Kolkata",
    price: 4500,
    rating: 4.4,
    location: "New Town",
    availableRooms: 25,
    createdBy: "admin-1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "hotel-5",
    name: "Hyatt Regency",
    city: "Kolkata",
    price: 8000,
    rating: 4.8,
    location: "Salt Lake",
    availableRooms: 18,
    createdBy: "admin-1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "hotel-6",
    name: "Taj Palace",
    city: "Delhi",
    price: 9000,
    rating: 4.9,
    location: "Chanakyapuri",
    availableRooms: 30,
    createdBy: "admin-1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "hotel-7",
    name: "The Leela Palace",
    city: "Delhi",
    price: 11000,
    rating: 5.0,
    location: "Diplomatic Enclave",
    availableRooms: 10,
    createdBy: "admin-1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "hotel-8",
    name: "The Lalit",
    city: "Mumbai",
    price: 7000,
    rating: 4.5,
    location: "Andheri",
    availableRooms: 22,
    createdBy: "admin-1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "hotel-9",
    name: "JW Marriott",
    city: "Mumbai",
    price: 9500,
    rating: 4.8,
    location: "Juhu",
    availableRooms: 14,
    createdBy: "admin-1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: "hotel-10",
    name: "Radisson Blu",
    city: "Bengaluru",
    price: 6000,
    rating: 4.3,
    location: "Whitefield",
    availableRooms: 35,
    createdBy: "admin-1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];